name: cast
version: 0.1.1
author: Dart Team <misc@dartlang.org>
description: Library for deep casting.
homepage: https://github.com/leafpetersen/cast
environment:
  sdk: '>=2.0.0-dev.0.0 <2.0.0'
dev_dependencies:
  test: ^0.12.0